tableau/TabPy

tabpy-server/tabpy_server/tabpy.py

A small PR for a feature allowing someone to specify a subdirectory in the state.ini where the TabPy server will be hosted. 
Closes #11 
Not sure about the implementation of the "get subdirectory from the state.ini" snippet. This should probably be in some config parser class. Thought about putting it in TabPyState, but I wasn't sure if this is the appropriate place.

Subdirectories for TabPy Server

---

tabpy-server/setup.py
tabpy-server/tabpy_server/tabpy.py

Hi,
I use Python a lot and I really enjoy Tableau, so I'm looking to merge the two together. I was digging through the installation docs but found the switching between pip and conda rather confusing. Digging deeper into the code from there, I noticed a lot of unused imports and PEP8 "violations."
While these violations in and of themselves don't cause bugs (i.e. have no effect on the runtime) on other projects there's typically a CI step that enforces coding standards and checks for unused imports to keep the package as clean as possible. I applied some LINTing here to the server `setup.py` and `tabpy.py` modules. I think it's worth doing this for all modules but this was a rather large first PR in and of itself, so I'm submitting as-is for your review.
One callout - there are still some …

Flake8 Support - LINTed setup and server tabpy

---

tabpy-server/tabpy_server/startup.py

Environment: Ubuntu 18.04 64 bit
Python 3.6
----
Steps to reproduce the error:
---
pip3 install tabpy-server
pip3 install tabpy-client
cd ~/.local/lib/python3.6/site-packages/tabpy_server
python3 startup.py
Operating system not recognized

Server fails to start in Ubuntu 18.04

---

docs/tabpy-tools.md

This is expected to fix the last of the broken links in this file.

fix all broken links in tabpy_tools.md

---

docs/tabpy-tools.md

server.md has been broken into separate files and this link needs to point to the REST docs

fix typo and broken link in tabpy-tools docs

---

.travis.yml
startup.sh

- Added TEST_ENV env variable flag to skip starting Python server in startup.sh
- Modified travis config to test startup script with TEST_ENV set
Testing done:
- Ran scripts in environment with and without TEST_ENV set

Modified travis config to run startup script.

---

.travis.yml
misc/TabPy.yml

Testing done:
- In swagger editor, manually verified the response schema is correct + generates the correct model.
- Verified it can parse the response from a local instance of TabPy server from the dev branch.

Update swagger config to parse new /info response schema.

---

tabpy-server/setup.py

this attr is only used for pip installs and we will not support pip install any longer

remove python_requires attribute

---

tabpy-server/setup.py

Many of these packages are included in a typical base install of Python.  Testing has revealed that different linux distributions will customize python installs and omit one or more of these packages.  Add all known discrepancies uncovered during testing to setup.py and add a comment to this effect.

add required packages to setup.py

---

CHANGELOG
CONTRIBUTING.md
docs/server-config.md
docs/tabpy-tools.md

Update documentation for how to use `set_credentials`

Dev tools doc

---

tabpy-server/server_tests/test_pwd_file.py

there was already a test for this condition but since it was missing a \n character it caused a different failure - too many arguments on a single line of the pwd file
change that test name to be more accurate and add a test for duplicate usernames
this is expected to hit 100% of app\util.py

add test for mult entries

---

startup.cmd
startup.sh
tabpy-server/server_tests/test_config.py
tabpy-server/server_tests/test_pwd_file.py
tabpy-server/tabpy_server/app/app.py

Manually tested on both Mac & Windows creating a temporary config file and passing it in on startup

weren't setting the path properly for the optional config parameter

---

tabpy-server/tabpy_server/app/app.py
tabpy-server/tabpy_server/app/util.py

While debugging and starting/stopping server multiple times to toggle auth state I found it easier to just clearly log the auth state enabled or not enabled

Add logging to make auth state more clear

---

tabpy-tools/tools_tests/test_rest.py

this codepath had not been tested before

add test for missing trailing slash for endpoint

---

tabpy-server/server_tests/test_service_info_handler.py

since this actually goes through tornado this should be sufficient for E2E to validate the info response for auth on (already tested) and auth off (this test)

add test to validate info response with auth off

---

docs/TableauConfiguration.md

Tableau Server 2018.2 (Windows) / Tableau Server 10.5 (Linux) and Newer Versions:

command updated

---

docs/TableauConfiguration.md
startup.cmd
startup.sh

Updated startup scripts for when there are spaces in the path where TabPy is running from.

Fix for paths with spaces

---

startup.cmd
startup.sh

Change: 
If python version is below 3.6, print an error to console, and block the start up, since it won't success anyway.
If python version is below 3.6.5, print a warning to console, without blocking the start up.
Related Task: 
https://tfs.tsi.lan/tfs/DefaultCollection/Tableau-Dev/Advanced%20Analytics%20-%20(Augmented%20Analytics%20Area)/_workitems?id=913569&triage=true&_a=edit

Print a warning/error if python version is not as required

---

tests/integration/test_deploy_model_ssl_off_auth_off.py

When writing the new integration test for models (test_deploy_and_evaluate_model.py) I accidentally overwrote an existing test (test_deploy_model_ssl_off_auth_off.py), reverting this test back.

Restoring overwritten test

---

tabpy-server/tabpy_server/handlers/management_handler.py

the ednpoint path no longer allowed for periods and tabpy releases contain them (ex - TabPy-0.6) so model deployment was failing

fixing regex issue where . were not allowed in endpoint path

---

.vscode/settings.json
tabpy-server/tabpy_server/app/app.py
tabpy-server/tabpy_server/handlers/base_handler.py
tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
tabpy-server/tabpy_server/state.ini
tests/integration/integ_test_base.py
tests/integration/test_deploy_and_evaluate_model_ssl.py
tests/unit/server_tests/test_config.py

* In HTTPS mode models called with /evaluate will be invoked with correct URL (starting with https://)
* Added integration test for the case
* Fixed some styling

Fix models call via /evaluate in HTTPS

---

docs/server-startup.md

Correct documentation to show the correct relative path for providing a custom configuration file at the command line start up.
Fixes #334

Correct Path reference to custom config file

---

docs/server-config.md
tabpy/tabpy_server/app/app.py
tests/unit/server_tests/test_config.py

Environment variables can now be used in the config file such that `%(ENV_VAR)s` will be parsed as the value of the environment variable `ENV_VAR`.

Enable config file to parse environment variables.

---

docs/tabpy-virtualenv.md

Updated tabpy-virtualenv.md. The activation for OS Linux and Mac requires the word "source" in order for the virtualenv to activate.

Updated tabpy-virtualenv.md

---

tabpy/tabpy_server/common/messages.py
tabpy/tabpy_server/handlers/base_handler.py
tabpy/tabpy_server/management/state.py
tabpy/tabpy_server/psws/python_service.py
tabpy/tabpy_tools/client.py
tabpy/tabpy_tools/rest.py
tabpy/tabpy_tools/rest_client.py

Inheriting from object is a Python 2 relic of "new style classes"; not applicable with Python3

Removed old py2 inheritance

---

tabpy/tabpy_server/handlers/base_handler.py
tabpy/tabpy_server/handlers/endpoint_handler.py
tabpy/tabpy_server/handlers/endpoints_handler.py
tabpy/tabpy_server/handlers/evaluation_plane_handler.py
tabpy/tabpy_server/handlers/query_plane_handler.py
tabpy/tabpy_server/handlers/service_info_handler.py
tabpy/tabpy_server/handlers/status_handler.py
tabpy/tabpy_server/handlers/upload_destination_handler.py
tabpy/tabpy_server/handlers/util.py
tests/unit/server_tests/test_endpoint_handler.py
tests/unit/server_tests/test_endpoints_handler.py
tests/unit/server_tests/test_evaluation_plane_handler.py
tests/unit/server_tests/test_service_info_handler.py

When TabPy receives a request with authN credentials, and it it not configured with authentication enabled, it should ignore it and return with a 200 status. Instead, it should return a 400 Bad Request status.
I created another flag authentication_not_required_error that tracks if this specific case happens. I also changed the not_authorized error flag to be authentication_error flag as it now encompasses more than just user not being authorized. The checks in each of the endpoints are also updated to reflect the new scenario and unit tests have been written to test this scenario.

Return HTTP 400 status when receiving a request with authentication credentials and authN is not configured

---

tabpy/tabpy_tools/rest_client.py

this method accepts a cls value but then immediately reassigns it.  Fix this code smell to make this file a tiny bit easier to maintain by introducing a new variable name

use a new argument in rest_client.py

---

docs/security.md
docs/server-config.md
tabpy/tabpy_server/app/app.py
tabpy/tabpy_server/app/app_parameters.py
tabpy/tabpy_server/common/default.conf
tabpy/tabpy_server/handlers/__init__.py
tabpy/tabpy_server/handlers/base_handler.py
tabpy/tabpy_server/handlers/evaluation_plane_handler.py
tabpy/tabpy_server/handlers/service_info_handler.py
tests/unit/server_tests/test_evaluation_plane_handler.py
tests/unit/server_tests/test_service_info_handler.py

For security reasons, some clients want to turn off ad hoc python scripts.
Added a new parameter "TABPY_EVALUATE_ENABLE" to TabPy’s configuration file (True by default)
It will serve as a toggle control to TabPy’s evaluate endpoint

Add toggle to turn off evaluate API

---

tabpy/tabpy_server/static/index.html

This URL (http://tabscifi.com/) is not being used so it could be a potential security concern

Remove broken URL

---

docs/tabpy-tools.md

This link broke with change 7fe5d93f9e946fa967e4a8c112b3aa4a0272e0d4 back on 4/29/2019 when the evaluate command was removed.  Just point to the rest docs in general

fix link in tabpy-tools

---

README.md
docs/server-config.md

- Documentation update: add a note for running TabPy without authentication. A follow up to https://github.com/tableau/TabPy/pull/612.
- Documentation update: remove reference to logging Tableau Server username (currently not supported).

Security: Add README note for running TabPy without authentication

---

.scrutinizer.yml

Override `python setup.py install` with `pip install .` in scrutinizer.
Example of failing scrutinizer: https://scrutinizer-ci.com/g/tableau/TabPy/inspections/b52bcab3-75ee-49ea-bd47-2692be0eb2cf
Example of successful scrutinizer (this PR): https://scrutinizer-ci.com/g/tableau/TabPy/inspections/13c4c6e1-8bcb-4a59-ad10-0d41e400e32d

Fix Scrutinizer-CI Failing Dependencies Step

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
docs/server-install.md

Confirmed that we do support up to python 3.10. Added this to documentation and added supported python versions to the series of tests run on a pull request

updated docs and tests to include python 3.10

---

docs/tabpy-tools.md

W-14276657: Updating deploy and update_endpoint_info documentation in tabpy_tools

---

docs/tabpy-tools.md
tabpy/tabpy_server/handlers/endpoint_handler.py
tabpy/tabpy_tools/client.py
tabpy/tabpy_tools/rest_client.py

Updated set_endpoint to take an optional parameter that determines whether or not we should update an endpoints version. In the case of update_endpoint_info we are updating an endpoints metadata and so we do not want to update the version. In the case of deploy, we will default to updating the version.

W-16337942: updating update_endpoint_info to not increment endpoint version

---

tabpy/tabpy_server/management/state.py

update_endpoint_info, and deploy with override set to True were both broken when trying to update a function that had been deployed before is_public existed.
The update code searched for the is_public attribute, and failed when it did not exist. To fix this, when updating a function we first check that is_public exist, and if it does not we default it False if no specific value is set in deploy or update.

W-17092332: Fix for updating functions without is_public set
