tableau/TabPy

server.md

setup.sh did not have permissions and sudo ./setup.sh won't work

Fixed issue on Sierra

---

tabpy-client/tabpy_client/client.py
tabpy-server/tests/test_client.py

client unittest failing

---

server.md
tabpy-server/tabpy_server/common/config.py
tabpy-server/tabpy_server/common/config.py.template
tabpy-server/tabpy_server/common/endpoint_file_mgr.py
tabpy-server/tabpy_server/psws/callbacks.py
tabpy-server/tabpy_server/tabpy.py
tabpy-server/tests/test_config.py

#91 
starting point for any discussion which may be needed

Proposed code maintenance - configuration

---

setup.bat

to set environment variables correctly inside IF blocks, the name of the variable needs to be in quotes
set help to get the man page

Change setup.bat:  PYTHONPATH inside IF blocks #56

---

tabpy-server/tabpy_server/psws/callbacks.py
tabpy-server/tabpy_server/psws/python_service.py
tabpy-server/tabpy_server/startup.py

Lot's of flakes here
**master**
```sh
$ flake8 | wc -l
503
```
**more-flake8**
```sh
$ flake8 | wc -l
379
```

LINTed psws folder

---

startup.cmd
startup.sh

Updated startup scripts to include output from tabpy-server and tabpy-tools install.

Bug fix: install logs were only showing output from tabpy-tools install.

---

docs/server-startup.md

The CENTOS link is not valid and some small grammar fixes

remove broken link and fix minor typos

---

docs/TableauConfiguration.md

change link to point to tabpy-tools.md instead of client.md

fix broken link

---

docs/server-config.md

clean up grammar a bit and fix the filename and location for the startup files

fix typos and filenames

---

.travis.yml

- Added config file for enabling travis CI.

Add travis CI.

---

.travis.yml

- Now running tests with coverage.
- Added coveralls check to CI.
Code coverage should now be reported in PRs (as demonstrated in this one). :)

Add code coverage to PRs.

---

tabpy-tools/client_tests/test_client.py
tabpy-tools/tabpy_tools/client.py
tabpy-tools/tabpy_tools/rest.py

Remove unused verify_certificate parameter in Client and session

Remove unused verify_certificate parameter in Client and session

---

.travis.yml
CONTRIBUTING.md
README.md
docs/TableauConfiguration.md
docs/about.md
docs/security.md
docs/server-config.md
docs/server-configurations.md
docs/server-download.md
docs/server-rest.md
docs/server-startup.md
docs/tabpy-tools.md

Add markdownlint step

---

docs/server-startup.md
tabpy-server/setup.py

six is a required package

---

tabpy-server/server_tests/test_config.py
tabpy-server/setup.py
tabpy-tools/setup.py
tabpy-tools/tabpy_tools/rest.py

Cleanup Unneeded Modules in Setup

---

tabpy-tools/tabpy_tools/__init__.py
tabpy-tools/tabpy_tools/client.py
tabpy-tools/tabpy_tools/custom_query_object.py
tabpy-tools/tabpy_tools/query_object.py
tabpy-tools/tabpy_tools/rest.py
tabpy-tools/tabpy_tools/rest_client.py
tabpy-tools/tabpy_tools/schema.py
tabpy-tools/tools_tests/test_client.py
tabpy-tools/tools_tests/test_rest.py
tabpy-tools/tools_tests/test_rest_object.py

To improve styling and reduce bugs. Ideally will have something like autopep8 set up in the future to catch these as part of CI

Flake8 of tabpy-tools

---

tabpy-tools/tabpy_tools/__init__.py
tabpy-tools/tabpy_tools/client.py
tabpy-tools/tabpy_tools/custom_query_object.py
tabpy-tools/tabpy_tools/query_object.py
tabpy-tools/tabpy_tools/rest.py
tabpy-tools/tabpy_tools/rest_client.py
tabpy-tools/tabpy_tools/schema.py
tabpy-tools/tools_tests/test_client.py
tabpy-tools/tools_tests/test_rest.py
tabpy-tools/tools_tests/test_rest_object.py

Copy code improvements from https://github.com/tableau/TabPy/pull/205 to dev branch
@WillAyd

Duplicate PR 205 improvements for dev branch

---

tabpy-server/tabpy_server/common/endpoint_file_mgr.py
tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py

The bug was caused by code change where we started treating each entry in config file as a string instead of parsing port as int and so on.

Fix restricted evaluation bug

---

tabpy-server/tabpy_server/handlers/util.py

Fix typos for logging in util.py

---

utils/user_management.py

there was an unwanted set of parenthesis around the name and password causing tuple index errors

Fix tuple index out of range error

---

utils/user_management.py

update grammar in strings
add log message for successfully updating file
removed ... from log strings to make copying from console easier

grammar and logging updates

---

.travis.yml
CI/inc_ver.py

With this CI script we can have commit as a part of TabPy version

Add CI version update script

---

tabpy-server/server_tests/test_pwd_file.py
tabpy-server/tabpy_server/app/util.py

If the password file had a username followed by a space, parsing would succeed and set the user password to null
add a check to fail parsing and log a warning about this conditin

update pw file parser

---

.travis.yml
startup.sh
tabpy-server/setup.py

Issue: setup.py did not specify the compatible range of urllib3 versions
Fix: print install scripts in travis builds as a debugging measure, add version requirements to urllib3

Build is broken.

---

CONTRIBUTING.md
docs/api-v1.md
docs/server-config.md
docs/server-rest.md

Misc. grammar fixes and typos fixed

fixing typos/grammar in docs

---

.coveragerc
CONTRIBUTING.md
tabpy-server/tabpy_server/app/app.py
tabpy-server/tabpy_server/app/util.py
tabpy-server/tabpy_server/common/endpoint_file_mgr.py
tabpy-server/tabpy_server/common/util.py
tabpy-server/tabpy_server/handlers/base_handler.py
tabpy-server/tabpy_server/handlers/endpoint_handler.py
tabpy-server/tabpy_server/handlers/endpoints_handler.py
tabpy-server/tabpy_server/handlers/evaluation_plane_handler.py
tabpy-server/tabpy_server/handlers/management_handler.py
tabpy-server/tabpy_server/handlers/query_plane_handler.py
tabpy-server/tabpy_server/handlers/util.py
tabpy-server/tabpy_server/management/state.py
tabpy-server/tabpy_server/management/util.py
tabpy-server/tabpy_server/psws/callbacks.py
tabpy-server/tabpy_server/psws/python_service.py
tabpy-tools/tabpy_tools/client.py
tabpy-tools/tabpy_tools/custom_query_object.py
tabpy-tools/tabpy_tools/query_object.py
tabpy-tools/tabpy_tools/rest.py
tabpy-tools/tabpy_tools/schema.py
tests/unit/server_tests/test_endpoint_handler.py
tests/unit/server_tests/test_endpoints_handler.py
tests/unit/server_tests/test_evaluation_plane_handler.py
tests/unit/server_tests/test_pwd_file.py
tests/unit/server_tests/test_service_info_handler.py
utils/user_management.py

- Remove dead code (detected with vulture)
- replace %s, %r in strings with f-strings
- replaced .format() for strings with f-strings
- removed Unicode specific logic - Python 3 supports it natively
- removed checks for Python version to be higher than 3.0 - it is a prerequirement for TabPy

Dev remove dead code

---

tabpy-server/tabpy_server/handlers/management_handler.py

fixing regex issue where . were not allowed in endpoint path (#305)

---

CONTRIBUTING.md

Added coverage module to required pip package list

Added coverage as a dev requirement (#341)

---

tabpy/models/deploy_models.py
tabpy/models/utils/setup_utils.py
tabpy/tabpy.py
tabpy/tabpy_server/app/ConfigParameters.py
tabpy/tabpy_server/app/app.py
tabpy/tabpy_server/common/messages.py
tabpy/tabpy_server/handlers/endpoint_handler.py
tabpy/tabpy_server/handlers/management_handler.py
tabpy/tabpy_server/handlers/query_plane_handler.py
tabpy/tabpy_server/handlers/upload_destination_handler.py
tabpy/tabpy_server/handlers/util.py
tabpy/tabpy_server/management/state.py
tabpy/tabpy_server/psws/callbacks.py
tabpy/tabpy_server/psws/python_service.py
tabpy/tabpy_tools/client.py
tabpy/utils/user_management.py

Fix vulnerabilities found by LGTM

Fix vulnerabilities found by LGTM

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
tabpy/tabpy_server/app/app.py
tests/integration/test_auth.py
tests/integration/test_custom_evaluate_timeout.py
tests/integration/test_url.py

Improved functions:
*  app._parse_config

Code improvement (based on Scrutinizer recommendations)

---

docs/TableauConfiguration.md

server-startup doesn't seem to exist anymore. The link was broken.

Doc update

---

docs/tabpy-virtualenv.md

add additional instructions for Anaconda virtual environments, in a Windows environment

update tabpy-virtualenv for Anaconda

---

tabpy/tabpy_server/common/default.conf
tabpy/tabpy_server/handlers/base_handler.py
tests/integration/integ_test_base.py

Fix 500 error for when 401 should be returned.

remove print from error handling code

---

tabpy/tabpy_server/static/index.html

this will allow screen readers to work properly with this html

add lang attribute to html tag

---

MANIFEST.in

Closes https://github.com/tableau/TabPy/issues/472

MANIFEST.in: Add docs and test data

---

Procfile
app.json

- Add two config variables for Username + Password
- Add TABPY_PWD_FILE parameter & add an account

Added authentication for Heroku deployment

---

tabpy/tabpy_server/app/app.py
tabpy/tabpy_server/handlers/service_info_handler.py
tests/unit/server_tests/test_service_info_handler.py

Moved evaluate_enabled flag inside features field

Refactor /info response

---

README.md

looks like it needs the template parameter

Fixing the Deploy to Heroku button

---

README.md

Reverts tableau/TabPy#546
This need more review and approval from Tableau/Salesforce before publishing. I'll update in the comments when I have something.

Revert "Add "Support Ukraine" badge with link to National Bank of Ukraine's w…"

---

docs/server-config.md
tabpy/tabpy_server/app/app.py
tabpy/tabpy_server/app/app_parameters.py
tabpy/tabpy_server/app/arrow_server.py

- Leverages existing config-file framework to add custom GRPC port capability.
- Will accept via config file, environment variable, and if neither of those are present, fallback to default val.

Configurable GRPC port for Arrow Server

---

tabpy/tabpy_server/app/app.py
tabpy/tabpy_server/app/app_parameters.py
tabpy/tabpy_server/handlers/evaluation_plane_handler.py

This allows users to enable/disable Arrow support via a config setting.

Arrow is enabled via config
